### PR TITLE
Create _TZE200_2aaelwxk

### PR DESCRIPTION
**Pull request by szczeslaw**
ZG-205Z-A presence sensor.

### CODE REVIEW

**Comment by w35l3y** [comment]
Thanks for colaborating with the repository.

Please, send some evidences that corroborate with your PR.
Where did you get the model ?
Where did you get the manufacturer ?
Where did you get the list of datapoints ?

According to this file below, the model is TS0225, not TS0601.
https://github.com/Koenkk/zigbee-herdsman-converters/blob/b930eeec4761370e4202d2c483f720eec5381f7f/src/devices/tuya.ts#L4825

The folder and filename must match exactly with your device. Otherwise, it won't find it.

**Comment by w35l3y** [comment]
Also, there is device from the TS0225 folder that uses another profile.

What made you to choose the existing profile "normal-presenceSensor-v1" ?

**Comment by szczeslaw** [comment]
Hi,
I got those presence sensors from Aliexpress, and just yesterday connected one to SmartThings.
Screenshot_20231025_115504_SmartThings
List of datapoints is coming from manufacturers converter file:
https://doc.szalarm.com/zg-205ZL/cntop_zigbee_sensor.js

Yes, actual model is TS0225, however from what i can see it's much more similar to to TS0601 presense sensors, and that what's actually chosen automatically by your driver in similarity mode.
Also profile fits much better than others, as this device needs settings to work properly.
I could probably create new profile for it one day, but not just yet.
Hope this answers your questions.

**Comment by szczeslaw** [comment]
But you are probably right, that i should've used TS0225 folder.

**Comment by w35l3y** [comment]
Please, test the beta version so I can send it to the main.

**Comment by w35l3y** [comment]
Here is the invitation link of the beta version:

https://bestow-regional.api.smartthings.com/invite/VbMb856WP8lB

**Comment by w35l3y** [comment]
@szczeslaw , if no test is made, then I will need to revert the changes.

Could you test the beta version as mentioned before?

**Comment by w35l3y** [comment]
As there wasn't any response for 2 weeks, I had to revert it back.
Thanks for coding, but testing is also needed.
Consider opening a new PR when you some have time to test it.

**Pull request merged**
