### PR TITLE
ZG-205Z-B presence sensor.

### PR DESCRIPTION
**Pull request by arielgr**
Hi @w35l3y !
Noticed there was an attempt in the past to add the ZG-205Z-A presence sensor, but it was never eventually merged.
Adding here a slightly more complete mapping for ZG-205Z-B (a 24G version of ZG-205Z-A) which is identified as the same device  - _TZE200_2aaelwxk

### CODE REVIEW

**Comment by arielgr** [comment]
I am attempting a pull request with the best of my limited knowledge... I haven't been able to test this.. also was not able to run npm start as I am fully working online... if there's a way you can guide me happy to do it.. :)
Thanks!!!

**Comment by arielgr** [comment]
I run a test (call_test_driver) which completed successfully:
https://github.com/arielgr/EdgeDrivers/actions/workflows/call-test-driver.yaml

**Comment by arielgr** [comment]
@w35l3y can you please review this PR from a while back?

**Comment by w35l3y** [comment]
I have already reviewed it, but you ignored it and added a new profile.
I didn't get the point of the new profile.

**Comment by arielgr** [comment]
Oh sorry, I did not see that you reviewed it. For some reason I didn't get
any notice on it.
Appreciate if you could review the new profile (I understood it's
sufficiently different that a new one is better).

Thank you!!

**Pull request closed without merging**
