### PR TITLE
Create _TZE204_p3lqqy2r.yaml and  normal-thermostat-v6.yaml

### PR DESCRIPTION
**Pull request by Aneshen62**
Hello.  I`ve added new device , Touch thermostat 16A 2.0 and an profile for it witch includes Floor temp at the top and energy meter and power meter at group 3.  Room temp is at group 2 ( For users using floor temp)  Is this possible to implement ?  

Thanks in advanced.

### CODE REVIEW

**Comment by w35l3y** [comment]
Thanks for your help.

I am not accepting profiles anymore, only models.

The ST platform limits each driver to 100 profiles.

**Comment by Aneshen62** [comment]
Thanks for reviewing this .  That is sad.  Then I see no use for these files.  

Cheers

**Comment by Aneshen62** [comment]
Im new with this.  Is it possible for me to use the driver locally for my own purposes ?  Need to set up ST CLI ?

**Comment by w35l3y** [comment]
> Im new with this. Is it possible for me to use the driver locally for my own purposes ? Need to set up ST CLI ?

Yes, create your own channel, publish the driver to your channel and install it.
You won't need to create an invitation link to use locally.

https://developer.smartthings.com/docs/devices/hub-connected/driver-channels

You may use the github workflow to publish the driver for you but it will require you to define 2 variables:
* SMARTTHINGS_CHANNEL (public)
* SMARTTHINGS_TOKEN (secret)

**Comment by Aneshen62** [comment]
Hello Wesley .  I have done the setup for my private channel, enrolled drivers and modified it with floor temp and energy as the change from Thermostat v3 profile .  Only issue i have is that the energy meter is showing as first desimal , 75W instead of 750 . Rate in the DP is 0 , so no rate for this DP . Is it possible to set rate as an negative value ?   Thanks for providing me with guidance and learning LUA and the CLI commands . Fun enviroment.  Best regards Anders

**Comment by Aneshen62** [comment]
Got it .  At no rate it reported 75W .  Had to set it to rate 100 .  Seems right .. ish

**Comment by Aneshen62** [comment]
Hello again, Wesley .  Sorry if I bother you with this .  One question.  When I try to add an command in command.lua,  Swing temperature(copied form set temperaure , just edited the name) , I get error code 400,  wrong device profile.  The name of the command is in the device Yaml, device lua file and the profile.  I modify the files and add them with CLI .  Is there something I`m missing ?  Thanks in advanced.

**Comment by w35l3y** [comment]
I didn't understand.
When exactly the error is reported ?
Could you share the code ?

**Comment by Aneshen62** [comment]
@w35l3y  Hello.  As I wrote in the forum,  I've seen a code to reset the energy meter. It's at basic 0x00 with command 0 and Payload {} . Could you provide me some guidance to modify the current code? Currently it's tuya.types Int32 (0).

**Comment by w35l3y** [comment]
How do you expect to send this command ?

I haven't tested it with a direct command without an attribute, but take momentaryStd or switchStd as examples.
You must know the cluster name (which I think it is "Basic" and you should inform it in "cluster") and the command name (which you should inform it in "custom_command")

**Comment by Aneshen62** [comment]
Thanks! Yes. 😬 I'll try that.  Not so sure about the payload tough.  At Ha forum, the guy specified it to be {} nothing.  One guy placed "0" and the unit did not respond afterwards

**Comment by Aneshen62** [comment]
Failed .  Here`s the log: 
2024-12-29T23:48:18.472473825+01:00 INFO Personal Tuya Devices - main  <ZigbeeDevice (Thermostat - namron)> received command: {"args":{},"capability":"energyMeter","command":"resetEnergyMeter","component":"main","positional_args":{}}
2024-12-29T23:48:18.475879221+01:00 TRACE Personal Tuya Devices - main  Found CapabilityCommandDispatcher handler in personal-tuya-devices -> GenericEF00 -> Model
2024-12-29T23:48:18.477415179+01:00 ERROR Personal Tuya Devices - main  Thermostat - namron thread encountered error: [string "st/dispatcher.lua"]:267: Error encountered while processing event for <ZigbeeDevice] (Thermostat - namron)>:
    arg1: {args={}, capability="energyMeter", command="resetEnergyMeter", component="main", positional_args={}}

**Comment by Aneshen62** [comment]
Probably code line 403 in cluster_base is the recipe?

**Comment by w35l3y** [comment]
> Probably code line 403 in cluster_base is the recipe?

I can't say for sure. I don't have access to your code.

**Comment by Aneshen62** [comment]
My code is similar to yours. I think a specific handler like mcu.synctime needs to be written because it seems like the command delivered is default handled in ef00 always. It's not possible to add momentarystd or switchstd without DP in the profile or model files

**Comment by w35l3y** [comment]
If the datapoint doesn't matter to you, then try informing a non-existent value, like 0 or -999

**Comment by Aneshen62** [comment]
**Thanks .  I tried but then it required an new device :**  
2024-12-30T22:41:15.751104313+01:00 INFO Personal Tuya Devices - main  Added device     TS0001  _TZ3210_dse8ogfy_wip    9
2024-12-30T22:41:15.751825876+01:00 WARN Personal Tuya Devices - main  Encountered error calling can_handle for dispatcher defaulting to false: [string "tuyaEF00_model_defaults.lua"]:167: [string "models/init.lua"]:2: [string "utils.lua"]:270: attempt to call a nil value (field '?')
2024-12-30T22:41:15.752395167+01:00 DEBUG Personal Tuya Devices - main  Thermostat - namron device thread event handled
2024-12-30T22:41:21.838884203+01:00 TRACE Personal Tuya Devices - main  Received event with handler capability
2024-12-30T22:41:21.851459682+01:00 INFO Personal Tuya Devices - main  <ZigbeeDevice:] (Thermostat - namron)> received command: {"args":{},"capability":"momentary","command":"push","component":"main02","positional_args":{}}
2024-12-30T22:41:21.852466620+01:00 INFO Personal Tuya Devices - main  Added device     TS0001  _TZ3210_dse8ogfy_wip    9
2024-12-30T22:41:21.853279599+01:00 WARN Personal Tuya Devices - main  Encountered error calling can_handle for dispatcher defaulting to false: [string "tuyaEF00_model_defaults.lua"]:167: [string "models/init.lua"]:2: [string "utils.lua"]:270: attempt to call a nil value (field '?')
2024-12-30T22:41:21.853824099+01:00 INFO Personal Tuya Devices - main  Added device     TS0001  _TZ3210_dse8ogfy_wip    9 "
2024-12-30T22:41:21.854273161+01:00 WARN Personal Tuya Devices - main  Encountered error calling can_handle for dispatcher defaulting to false: [string "tuyaEF00_model_defaults.lua"]:167: [string "models/init.lua"]:2: [string "utils.lua"]:270: attempt to call a nil value (field '?')
2024-12-30T22:41:21.856149703+01:00 TRACE Personal Tuya Devices - main  Found CapabilityCommandDispatcher handler in personal-tuya-devices -> GenericEF00
2024-12-30T22:41:21.857398161+01:00 DEBUG Personal Tuya Devices - main  Thermostat - namron device thread event handled


**im to Noob at this  :P  Seems like whatever I do , it tries to find the command at "generiEF00"  as the Model capability is there.  Ive added Genereric_body.GenericBody in the command , but the capability has to be "energyMeter" and its listed in EF00 .  Thanks anyways for looking at this ,**

**Pull request closed without merging**
